import { FormEvent, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AppShell, PageStatus } from './ui';
import { createApiClient } from './core/api';
import type { ApiClient } from './core/api';
import './app.css';

type Obligation = Record<string, unknown> & { id: string; student_id?: string | null; amount?: string | number; original_amount?: string | number; source?: string | null; category?: string | null; reason?: string | null; lifecycle_state?: string | null; originating_branch_id?: string | null; current_home_branch_id?: string | null };
type Payment = Record<string, unknown> & { id: string; student_id?: string | null; amount?: string | number; method?: string | null; received_on?: string | null; originating_branch_id?: string | null; current_home_branch_id?: string | null };
type Student = { id: string; student_code: string; person?: { legal_name?: string | null } | null; current_home_branch_id?: string | null; originating_branch_id?: string | null; current_home_branch?: { name?: string | null } | null };
type StudentsResponse = { students: Student[] };

function humanize(value: string): string { return value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function recordDate(value: unknown): string { return typeof value === 'string' ? value.slice(0, 10) : 'Date unavailable'; }
function recordText(value: unknown, fallback: string): string { return typeof value === 'string' && value !== '' ? value : fallback; }

function FinanceRecordTable({ kind, items, studentName, branch, onSelect }: { kind: 'obligation' | 'payment'; items: Array<Obligation | Payment>; studentName: (id?: string | null) => string; branch: (item: Obligation | Payment) => string; onSelect: (item: Obligation | Payment) => void }) {
  return <div className="table-wrap"><table><thead><tr>{kind === 'obligation' ? <><th>Record</th><th>Student</th><th>Amount</th><th>Source</th><th>State</th><th>Provenance</th></> : <><th>Record</th><th>Student</th><th>Amount</th><th>Method</th><th>Received</th><th>Provenance</th></>}</tr></thead><tbody>{items.map((item) => <tr key={item.id}>
    <td><button className="table-link" type="button" onClick={() => onSelect(item)}>{item.id}</button>{kind === 'obligation' && <small>{recordText(item.category, 'Uncategorized')}</small>}</td>
    <td>{studentName(item.student_id)}</td><td><strong>{String(item.amount ?? item.original_amount ?? '—')}</strong></td>
    {kind === 'obligation' ? <><td>{recordText(item.source, '—')}<small>{recordText(item.reason, '')}</small></td><td><span className={`status-chip ${item.lifecycle_state ?? ''}`}>{humanize(recordText(item.lifecycle_state, 'recorded'))}</span></td></> : <><td>{humanize(recordText(item.method, 'unknown'))}</td><td>{recordDate(item.received_on)}</td></>}
    <td>{branch(item)}</td>
  </tr>)}</tbody></table></div>;
}

function FinanceApp({ getJson, postJson, csrfToken }: ApiClient & { csrfToken: string }) {
  const [obligations, setObligations] = useState<Obligation[]>([]);
  const [payments, setPayments] = useState<Payment[]>([]);
  const [students, setStudents] = useState<Student[]>([]);
  const [selected, setSelected] = useState<{ kind: 'obligation' | 'payment'; item: Obligation | Payment } | null>(null);
  const [tab, setTab] = useState<'overview' | 'obligations' | 'payments'>('overview');
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [paymentForm, setPaymentForm] = useState({ period_id: '', student_id: '', amount: '', method: 'cash', payer_ref: '', received_on: '' });
  const [obligationForm, setObligationForm] = useState({ period_id: '', student_id: '', source: 'tuition', reason: '', category: 'tuition', amount: '', source_ref: '', offering_id: '' });
  const [refund, setRefund] = useState({ period_id: '', amount: '', reason: '' });
  const [busy, setBusy] = useState(false);
  const load = () => { setLoading(true); setError(null); void Promise.all([getJson<{ obligations: Obligation[] }>('/finance/obligations'), getJson<{ payments: Payment[] }>('/finance/payments'), getJson<StudentsResponse>('/students')]).then(([o, p, s]) => { setObligations(o.obligations ?? []); setPayments(p.payments ?? []); setStudents(s.students ?? []); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Finance data could not be loaded.')).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, []);
  const studentName = (id?: string | null) => { const student = students.find((item) => item.id === id); return student?.person?.legal_name ?? student?.student_code ?? id ?? 'Student not identified'; };
  const branch = (item: Obligation | Payment) => item.current_home_branch_id ?? item.originating_branch_id ?? 'Provenance unavailable';
  const visibleObligations = useMemo(() => { const term = query.trim().toLowerCase(); return !term ? obligations : obligations.filter((item) => `${item.id} ${item.student_id ?? ''} ${item.source ?? ''} ${item.category ?? ''} ${item.lifecycle_state ?? ''}`.toLowerCase().includes(term)); }, [obligations, query]);
  const visiblePayments = useMemo(() => { const term = query.trim().toLowerCase(); return !term ? payments : payments.filter((item) => `${item.id} ${item.student_id ?? ''} ${item.method ?? ''} ${item.received_on ?? ''}`.toLowerCase().includes(term)); }, [payments, query]);
  const command = (request: Promise<unknown>, success: string) => { setBusy(true); setError(null); setMessage(null); void request.then(() => { setMessage(success); load(); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Finance command was rejected.')).finally(() => setBusy(false)); };
  const submitPayment = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); command(postJson('/finance/payments', { ...paymentForm }), 'Payment recorded by the Finance authority.'); };
  const submitObligation = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); command(postJson('/finance/obligations', { ...obligationForm, offering_id: obligationForm.offering_id || undefined }), 'Obligation posted by the Finance authority.'); };
  const submitRefund = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selected || selected.kind !== 'payment') return; command(postJson(`/finance/payments/${encodeURIComponent(selected.item.id)}/refund`, refund), 'Refund proposed; a distinct Finance approver must record it.'); };
  if (loading) return <><AppShell current="finance" csrfToken={csrfToken} /><PageStatus>Loading authorized Finance facts…</PageStatus></>;
  return <><AppShell current="finance" csrfToken={csrfToken} /><main id="finance-main" className="workspace" aria-labelledby="finance-title">
    <header className="workspace-header"><div><p className="eyebrow">Finance · authoritative money surface</p><h1 id="finance-title">Money, shown with provenance.</h1><p className="lede">This workspace presents source-owned financial facts. React does not calculate balances or reinterpret ledger truth.</p></div><button className="button secondary" type="button" onClick={load}>Refresh facts</button></header>
    {error && <div className="alert" role="alert">{error}</div>}{message && <div className="notice" role="status">{message}</div>}
    <section className="summary-grid" aria-label="Finance record counts"><div className="panel"><span className="metric">{obligations.length}</span><span className="metric-label">Visible obligations</span></div><div className="panel"><span className="metric">{payments.length}</span><span className="metric-label">Visible payments</span></div><div className="panel"><span className="metric">{students.length}</span><span className="metric-label">Students in API scope</span></div><div className="panel"><span className="metric">API</span><span className="metric-label">Source of monetary truth</span></div></section>
    <div className="finance-guard"><strong>Authority boundary</strong><span>Amounts below are records returned by Finance. This UI intentionally does not derive a balance, outstanding amount, or settlement state in the browser.</span></div>
    <div className="student-tabs" role="tablist" aria-label="Finance work areas"><button role="tab" aria-selected={tab === 'overview'} aria-controls="finance-overview" tabIndex={tab === 'overview' ? 0 : -1} className={tab === 'overview' ? 'active' : ''} type="button" onClick={() => setTab('overview')}>Overview</button><button role="tab" aria-selected={tab === 'obligations'} aria-controls="finance-obligations" tabIndex={tab === 'obligations' ? 0 : -1} className={tab === 'obligations' ? 'active' : ''} type="button" onClick={() => setTab('obligations')}>Obligations <span aria-hidden="true">{obligations.length}</span></button><button role="tab" aria-selected={tab === 'payments'} aria-controls="finance-payments" tabIndex={tab === 'payments' ? 0 : -1} className={tab === 'payments' ? 'active' : ''} type="button" onClick={() => setTab('payments')}>Payments <span aria-hidden="true">{payments.length}</span></button></div>
    {(tab === 'overview' || tab === 'obligations') && <section id="finance-obligations" role="tabpanel" tabIndex={0} className="panel" aria-labelledby="obligations-heading"><div className="section-heading"><div><p className="eyebrow">Obligation register</p><h2 id="obligations-heading">What is recorded as due?</h2></div><span className="source-note">Finance API · branch scope server-enforced</span></div><label className="directory-filter">Filter obligations<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ID, student, source, category, state" /></label>{visibleObligations.length === 0 ? <p className="empty">No visible obligation records match the current filter.</p> : <FinanceRecordTable kind="obligation" items={visibleObligations} studentName={studentName} branch={branch} onSelect={(item) => setSelected({ kind: 'obligation', item })} />}</section>}
    {(tab === 'overview' || tab === 'payments') && <section id="finance-payments" role="tabpanel" tabIndex={0} className="panel" aria-labelledby="payments-heading"><div className="section-heading"><div><p className="eyebrow">Payment register</p><h2 id="payments-heading">Recorded receipts</h2></div><span className="source-note">Finance API · receipt facts are not balance calculations</span></div>{visiblePayments.length === 0 ? <p className="empty">No visible payment records match the current filter.</p> : <FinanceRecordTable kind="payment" items={visiblePayments} studentName={studentName} branch={branch} onSelect={(item) => setSelected({ kind: 'payment', item })} />}</section>}
    {tab === 'overview' && <section className="finance-command-grid"><section id="finance-overview" className="panel"><div className="section-heading"><div><p className="eyebrow">Command · payment</p><h2>Record receipt</h2></div><span className="source-note">Server validates period, student, amount, method and date</span></div><form onSubmit={submitPayment}><div className="compact-grid"><label>Financial period ID<input required value={paymentForm.period_id} onChange={(event) => setPaymentForm({ ...paymentForm, period_id: event.target.value })} /></label><label>Student<select required value={paymentForm.student_id} onChange={(event) => setPaymentForm({ ...paymentForm, student_id: event.target.value })}><option value="">Select a student…</option>{students.map((student) => <option key={student.id} value={student.id}>{student.person?.legal_name ?? student.student_code}</option>)}</select></label><label>Amount<input required inputMode="decimal" value={paymentForm.amount} onChange={(event) => setPaymentForm({ ...paymentForm, amount: event.target.value })} /></label><label>Method<input required value={paymentForm.method} onChange={(event) => setPaymentForm({ ...paymentForm, method: event.target.value })} /></label><label className="full-width">Payer reference<input required value={paymentForm.payer_ref} onChange={(event) => setPaymentForm({ ...paymentForm, payer_ref: event.target.value })} /></label><label>Received on<input required type="date" value={paymentForm.received_on} onChange={(event) => setPaymentForm({ ...paymentForm, received_on: event.target.value })} /></label></div><button className="button" type="submit" disabled={busy}>Record payment</button></form></section>
      <section className="panel"><div className="section-heading"><div><p className="eyebrow">Command · obligation</p><h2>Post obligation</h2></div><span className="source-note">No balance is computed in this form</span></div><form onSubmit={submitObligation}><div className="compact-grid"><label>Financial period ID<input required value={obligationForm.period_id} onChange={(event) => setObligationForm({ ...obligationForm, period_id: event.target.value })} /></label><label>Student<select required value={obligationForm.student_id} onChange={(event) => setObligationForm({ ...obligationForm, student_id: event.target.value })}><option value="">Select a student…</option>{students.map((student) => <option key={student.id} value={student.id}>{student.person?.legal_name ?? student.student_code}</option>)}</select></label><label>Source<input required value={obligationForm.source} onChange={(event) => setObligationForm({ ...obligationForm, source: event.target.value })} /></label><label>Category<input required value={obligationForm.category} onChange={(event) => setObligationForm({ ...obligationForm, category: event.target.value })} /></label><label>Amount<input required inputMode="decimal" value={obligationForm.amount} onChange={(event) => setObligationForm({ ...obligationForm, amount: event.target.value })} /></label><label>Source reference<input required value={obligationForm.source_ref} onChange={(event) => setObligationForm({ ...obligationForm, source_ref: event.target.value })} /></label><label className="full-width">Reason<input required value={obligationForm.reason} onChange={(event) => setObligationForm({ ...obligationForm, reason: event.target.value })} /></label></div><button className="button" type="submit" disabled={busy}>Post obligation</button></form></section></section>}
    {selected && <aside className="panel finance-detail" aria-labelledby="finance-detail-title"><div className="section-heading"><div><p className="eyebrow">Authoritative record</p><h2 id="finance-detail-title">{selected.kind === 'payment' ? 'Payment' : 'Obligation'} {selected.item.id}</h2></div><button className="text-button" type="button" onClick={() => setSelected(null)}>Close</button></div><dl className="detail-facts"><div><dt>Record</dt><dd>{selected.item.id}</dd></div><div><dt>Student</dt><dd>{studentName(selected.item.student_id)}</dd></div><div><dt>Amount</dt><dd>{String(selected.item.amount ?? selected.item.original_amount ?? '—')}</dd></div><div><dt>Status</dt><dd>{humanize(recordText(selected.item.lifecycle_state, 'recorded'))}</dd></div><div><dt>Provenance</dt><dd>{branch(selected.item)}</dd></div>{selected.kind === 'payment' && <div><dt>Received</dt><dd>{recordDate(selected.item.received_on)}</dd></div>}</dl>{selected.kind === 'payment' && <form onSubmit={submitRefund}><h3>Propose refund</h3><div className="compact-grid"><label>Financial period ID<input required value={refund.period_id} onChange={(event) => setRefund({ ...refund, period_id: event.target.value })} /></label><label>Amount<input required inputMode="decimal" value={refund.amount} onChange={(event) => setRefund({ ...refund, amount: event.target.value })} /></label><label className="full-width">Reason<input required value={refund.reason} onChange={(event) => setRefund({ ...refund, reason: event.target.value })} /></label></div><button className="button secondary" type="submit" disabled={busy}>Propose refund</button><p className="form-help">Proposal does not settle or reverse the payment. A distinct approver remains necessary.</p></form>}</aside>}
  </main></>;
}

const root = document.getElementById('finance-console');
if (root) {
  const csrfToken = root.getAttribute('data-csrf-token') ?? '';
  const api = createApiClient({ apiBase: root.getAttribute('data-api-base') ?? '/api/v1', csrfToken });
  api && createRoot(root).render(<FinanceApp {...api} csrfToken={csrfToken} />);
}
