import { FormEvent, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AppShell, PageStatus } from './ui';
import { createApiClient } from './core/api';
import type { ApiClient } from './core/api';
import './app.css';

type Person = { id: string; legal_name: string; verification_state: string; home_branch_id: string | null };
type Account = { id: string; person_id: string; username: string; account_state: string };
const humanize = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());

export function IdentityApp({ getJson, postJson, csrfToken }: ApiClient & { csrfToken: string }) {
  const [people, setPeople] = useState<Person[]>([]); const [accounts, setAccounts] = useState<Account[]>([]); const [query, setQuery] = useState(''); const [verifyPersonId, setVerifyPersonId] = useState('');
  const [registerForm, setRegisterForm] = useState({ legal_name: '', date_of_birth: '', home_branch_id: '' }); const [verifyForm, setVerifyForm] = useState({ identity_key: '', evidence_ref: '' });
  const [linkForm, setLinkForm] = useState({ person_id: '', username: '' }); const [passwordForm, setPasswordForm] = useState({ account_id: '', password: '' }); const [deactivateForm, setDeactivateForm] = useState({ account_id: '', reason: '' });
  const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  const load = () => { setLoading(true); setError(null); void Promise.all([getJson<{ people: Person[] }>('/identity/people'), getJson<{ accounts: Account[] }>('/identity/accounts')]).then(([peopleResponse, accountsResponse]) => { setPeople(peopleResponse.people ?? []); setAccounts(accountsResponse.accounts ?? []); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Identity records could not be loaded.')).finally(() => setLoading(false)); };
  useEffect(load, []);
  const command = (request: Promise<unknown>, success: string) => { setBusy(true); setError(null); setMessage(null); void request.then(() => { setMessage(success); load(); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Identity command was rejected.')).finally(() => setBusy(false)); };
  const register = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); command(postJson('/identity/people', registerForm), 'Person registered as a new identity record.'); setRegisterForm({ legal_name: '', date_of_birth: '', home_branch_id: '' }); };
  const verify = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!verifyPersonId) return; command(postJson(`/identity/people/${encodeURIComponent(verifyPersonId)}/verify`, verifyForm), 'Identity verification recorded.'); };
  const link = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); command(postJson('/identity/accounts', linkForm), 'User account linked to the identity.'); setLinkForm({ person_id: '', username: '' }); };
  const setPassword = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); command(postJson(`/identity/accounts/${encodeURIComponent(passwordForm.account_id)}/password`, { password: passwordForm.password }), 'Credential updated for the user account.'); setPasswordForm({ account_id: '', password: '' }); };
  const deactivate = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!window.confirm(`Deactivate account ${deactivateForm.account_id}? The account will no longer be able to authenticate.\n\nContinue?`)) return; command(postJson(`/identity/accounts/${encodeURIComponent(deactivateForm.account_id)}/deactivate`, { reason: deactivateForm.reason }), 'Account deactivation recorded.'); setDeactivateForm({ account_id: '', reason: '' }); };
  const visible = useMemo(() => { const term = query.trim().toLowerCase(); return term ? people.filter((person) => `${person.legal_name} ${person.id} ${person.home_branch_id ?? ''} ${person.verification_state}`.toLowerCase().includes(term)) : people; }, [people, query]);
  const accountPerson = (account: Account) => people.find((person) => person.id === account.person_id)?.legal_name ?? account.person_id;
  if (loading) return <><AppShell current="teachers" csrfToken={csrfToken} /><PageStatus>Loading authorized identity records…</PageStatus></>;
  return <><AppShell current="teachers" csrfToken={csrfToken} /><main id="workspace-main" className="workspace" aria-labelledby="identity-title">
    <header className="workspace-header"><div><p className="eyebrow">Identity authority</p><h1 id="identity-title">Identity before access.</h1><p className="lede">Identity registration and verification establish person records. Account lifecycle is shown separately from Access policy, positions, and effective permissions.</p></div><button className="button secondary" type="button" onClick={load}>Refresh identity records</button></header>
    {error && <div className="alert" role="alert">{error}</div>}{message && <div className="notice" role="status">{message}</div>}
    <section className="summary-grid"><div className="panel"><span className="metric">{people.length}</span><span className="metric-label">Visible identities</span></div><div className="panel"><span className="metric">{people.filter((p) => p.verification_state === 'verified').length}</span><span className="metric-label">Verified identities</span></div><div className="panel"><span className="metric">{accounts.length}</span><span className="metric-label">User accounts</span></div><div className="panel"><span className="metric">Separate</span><span className="metric-label">Access governance boundary</span></div></section>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Intake</p><h2>Register a person</h2></div><span className="source-note">Home branch is supplied to the identity command and authorized server-side.</span></div><form onSubmit={register}><div className="compact-grid"><label>Legal name<input required maxLength={160} value={registerForm.legal_name} onChange={(event) => setRegisterForm({ ...registerForm, legal_name: event.target.value })} /></label><label>Date of birth<input required type="date" value={registerForm.date_of_birth} onChange={(event) => setRegisterForm({ ...registerForm, date_of_birth: event.target.value })} /></label><label>Home branch id<input required value={registerForm.home_branch_id} onChange={(event) => setRegisterForm({ ...registerForm, home_branch_id: event.target.value })} /></label></div><button className="button" type="submit" disabled={busy}>{busy ? 'Registering…' : 'Register person'}</button></form></section>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Verified identity</p><h2>People in effective scope</h2></div><span className="source-note">{visible.length} visible record{visible.length === 1 ? '' : 's'}</span></div><label className="directory-filter">Filter identities<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Name, identity id, branch, verification state" /></label>{visible.length === 0 ? <p className="empty">No identity record matches the current scope or filter.</p> : <div className="table-wrap"><table><thead><tr><th>Person</th><th>Verification</th><th>Home branch</th><th>Actions</th></tr></thead><tbody>{visible.map((person) => <tr key={person.id}><td><strong>{person.legal_name}</strong><small>{person.id}</small></td><td><span className="status-chip">{humanize(person.verification_state)}</span></td><td>{person.home_branch_id ?? 'Not assigned'}</td><td><button className="text-button" type="button" onClick={() => { setVerifyPersonId(person.id); setVerifyForm({ identity_key: '', evidence_ref: '' }); }}>Verify</button><button className="text-button" type="button" onClick={() => setLinkForm({ person_id: person.id, username: '' })}>Link account</button></td></tr>)}</tbody></table></div>}</section>
    <section className="reporting-command-grid"><section className="panel"><div className="section-heading"><div><p className="eyebrow">Command · verification</p><h2>Verify identity</h2></div><span className="source-note">Verification requires an identity key and evidence reference.</span></div><form onSubmit={verify}><div className="compact-grid"><label>Person id<input required value={verifyPersonId} onChange={(event) => setVerifyPersonId(event.target.value)} /></label><label>Identity key<input required value={verifyForm.identity_key} onChange={(event) => setVerifyForm({ ...verifyForm, identity_key: event.target.value })} /></label><label className="full-width">Evidence reference<input required value={verifyForm.evidence_ref} onChange={(event) => setVerifyForm({ ...verifyForm, evidence_ref: event.target.value })} /></label></div><button className="button" type="submit" disabled={busy || !verifyPersonId}>Record verification</button></form></section>
      <section className="panel"><div className="section-heading"><div><p className="eyebrow">Command · account link</p><h2>Link a user account</h2></div><span className="source-note">Account linkage is not the same as granting permissions.</span></div><form onSubmit={link}><div className="compact-grid"><label>Person id<input required value={linkForm.person_id} onChange={(event) => setLinkForm({ ...linkForm, person_id: event.target.value })} /></label><label>Username<input required maxLength={120} value={linkForm.username} onChange={(event) => setLinkForm({ ...linkForm, username: event.target.value })} /></label></div><button className="button secondary" type="submit" disabled={busy}>Link user account</button></form></section></section>
    <section className="reporting-command-grid"><section className="panel"><div className="section-heading"><div><p className="eyebrow">Command · credential</p><h2>Set account credential</h2></div><span className="source-note">Password is transmitted only to the server command; it is never rendered back.</span></div><form onSubmit={setPassword}><div className="compact-grid"><label>Account<select required value={passwordForm.account_id} onChange={(event) => setPasswordForm({ ...passwordForm, account_id: event.target.value })}><option value="">Select account…</option>{accounts.filter((a) => a.account_state === 'active').map((account) => <option key={account.id} value={account.id}>{account.username} · {accountPerson(account)}</option>)}</select></label><label>New password<input required type="password" minLength={10} maxLength={255} value={passwordForm.password} onChange={(event) => setPasswordForm({ ...passwordForm, password: event.target.value })} /></label></div><button className="button" type="submit" disabled={busy || !passwordForm.account_id}>Set credential</button></form></section>
      <section className="panel"><div className="section-heading"><div><p className="eyebrow">Command · account lifecycle</p><h2>Deactivate account</h2></div><span className="source-note">Deactivation is irreversible for authentication until a separate governed reactivation capability exists.</span></div><form onSubmit={deactivate}><div className="compact-grid"><label>Account<select required value={deactivateForm.account_id} onChange={(event) => setDeactivateForm({ ...deactivateForm, account_id: event.target.value })}><option value="">Select account…</option>{accounts.filter((a) => a.account_state === 'active').map((account) => <option key={account.id} value={account.id}>{account.username} · {accountPerson(account)}</option>)}</select></label><label>Reason<input required maxLength={1000} value={deactivateForm.reason} onChange={(event) => setDeactivateForm({ ...deactivateForm, reason: event.target.value })} /></label></div><button className="button secondary" type="submit" disabled={busy || !deactivateForm.account_id || !deactivateForm.reason.trim()}>Deactivate account</button></form></section></section>
  </main></>;
}

const root = document.getElementById('identity-console');
if (root) { const csrfToken = root.getAttribute('data-csrf-token') ?? ''; const api = createApiClient({ apiBase: root.getAttribute('data-api-base') ?? '/api/v1', csrfToken }); createRoot(root).render(<IdentityApp {...api} csrfToken={csrfToken} />); }
