import { useEffect, useState } from 'react';
import { AppShell, PageStatus } from './ui';
import type { ApiClient } from './core/api';

type ManagementWorkspace = {
  scope: { type: string; organization_ids: string[]; branch_ids: string[] };
  counts: Record<string, number>;
  operational_health: Record<string, number | string>;
  latest_reports: Array<{
    id: string;
    period_key: string;
    result: string | null;
    completeness: 'complete' | 'incomplete' | null;
    evidence_status: 'complete' | 'incomplete' | 'historic_unclassified';
    created_at: string | null;
  }>;
};

type ManagementAppProps = ApiClient & { csrfToken: string };

function humanize(key: string): string {
  return key.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
}

export function ManagementApp({ getJson, csrfToken }: ManagementAppProps) {
  const [management, setManagement] = useState<ManagementWorkspace | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const loadManagement = () => {
    setLoading(true);
    setError(null);
    void getJson<{ data: ManagementWorkspace }>('/management')
      .then((response) => setManagement(response.data))
      .catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Management data could not be loaded.'))
      .finally(() => setLoading(false));
  };

  useEffect(() => { loadManagement(); }, []);

  if (loading) return <><AppShell current="management" csrfToken={csrfToken} /><PageStatus>Loading your authorized management workspace…</PageStatus></>;

  return (
    <>
      <AppShell current="management" csrfToken={csrfToken} />
      <main id="workspace-main" className="workspace" aria-labelledby="management-title">
        <header className="workspace-header">
          <div><p className="eyebrow">Governed decision support</p><h1 id="management-title">See the health of the operation.</h1><p className="lede">Management reads source-owned projections, reports, and operational health. It does not create tasks, alter money, or make lifecycle decisions.</p></div>
          <button className="button secondary" type="button" onClick={loadManagement} disabled={loading}>Refresh snapshot</button>
        </header>
        {error && <div className="alert" role="alert">{error}</div>}
        {management && <>
          <section className="panel management-scope" aria-labelledby="scope-heading">
            <div className="section-heading"><div><p className="eyebrow">Effective authorization</p><h2 id="scope-heading">{humanize(management.scope.type)} scope</h2></div><span className="source-note">Snapshot generated by the server</span></div>
            <p className="muted">Organizations: {management.scope.organization_ids.length ? management.scope.organization_ids.join(', ') : 'none in scope'}</p>
            <p className="muted">Branches: {management.scope.branch_ids.length ? management.scope.branch_ids.join(', ') : 'none in scope'}</p>
          </section>
          <section className="panel" aria-labelledby="management-counts-heading">
            <div className="section-heading"><div><p className="eyebrow">Source-linked measures</p><h2 id="management-counts-heading">Current operating counts</h2></div><span className="source-note">Read-only projection · values are not recalculated in React</span></div>
            <div className="management-grid">{Object.entries(management.counts).map(([key, value]) => <div key={key}><strong>{value}</strong><span>{humanize(key)}</span></div>)}</div>
          </section>
          <section className="panel" aria-labelledby="health-heading">
            <div className="section-heading"><div><p className="eyebrow">Operational health</p><h2 id="health-heading">Projection and integration signals</h2></div><span className="source-note">Unavailable sources remain explicit</span></div>
            <div className="health-grid">{Object.entries(management.operational_health).map(([key, value]) => <div key={key}><span>{humanize(key)}</span><strong>{String(value)}</strong></div>)}</div>
          </section>
          <section className="panel" aria-labelledby="reports-heading">
            <div className="section-heading"><div><p className="eyebrow">Governed reporting</p><h2 id="reports-heading">Latest report runs</h2></div><span className="source-note">{management.latest_reports.length} visible run{management.latest_reports.length === 1 ? '' : 's'}</span></div>
            <p className="muted">Incomplete or historic-unclassified report evidence remains auditable, but its numeric result is withheld from this decision-support view.</p>
            {management.latest_reports.length === 0 ? <p className="empty">No report run is available in this authorized scope.</p> : <ul className="report-list">{management.latest_reports.map((report) => <li key={report.id}><span><strong>{report.period_key}</strong><small>{report.created_at ?? 'Timestamp unavailable'}</small></span><span className="status-chip">{report.evidence_status === 'complete' ? humanize(report.result ?? '') : report.evidence_status === 'incomplete' ? 'Withheld — evidence incomplete' : 'Withheld — historic evidence unclassified'}</span></li>)}</ul>}
          </section>
        </>}
      </main>
    </>
  );
}
