import { FormEvent, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './app.css';
import { AppShell, PageStatus } from './ui';
import { createApiClient } from './core/api';

const root = document.getElementById('payroll-console');
const api = createApiClient({
  apiBase: root?.getAttribute('data-api-base') ?? '/api/v1',
  csrfToken: root?.getAttribute('data-csrf-token') ?? '',
});
const { getJson, postJson } = api;
const csrfToken = root?.getAttribute('data-csrf-token') ?? '';

function humanize(value: string): string { return value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function confirmAction(summary: string, irreversible = false): boolean {
  return window.confirm(`${summary}\n\n${irreversible ? 'This changes an official Payroll lifecycle and may be difficult to reverse.' : 'The server remains the authority for the resulting state.'}\n\nContinue?`);
}

type Period = { id: string; period_key: string; date_from: string; date_to: string; lifecycle_state?: string | null };
type Calculation = { id: string; employment_id: string; base_amount?: string | number | null; lifecycle_state?: string | null; period_id?: string | null; hold_reason?: string | null };
type Result = { id: string; employment_id: string; amount?: string | number | null; lifecycle_state?: string | null; originating_branch_id?: string | null };
type Clearance = { id: string; employment_id: string; domain: string; note?: string | null; lifecycle_state?: string | null };
type SettlementProposal = { id: string; employment_id: string; amount: string | number; basis: string; prepared_by?: string | null; lifecycle_state?: string | null };
type Employment = { id: string; person_id: string; lifecycle_state?: string | null };
type PayrollWorkspace = { periods: Period[]; calculations: Calculation[]; results: Result[]; employments: Employment[]; terminated_employments: Employment[]; clearances: Clearance[]; settlement_proposals: SettlementProposal[] };
type Tab = 'overview' | 'periods' | 'calculations' | 'settlements';

function PayrollApp() {
  const [data, setData] = useState<PayrollWorkspace | null>(null);
  const [tab, setTab] = useState<Tab>('overview');
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [periodForm, setPeriodForm] = useState({ period_key: '', date_from: '', date_to: '' });
  const [calculationForm, setCalculationForm] = useState({ period_id: '', employment_id: '' });
  const [selectedCalculation, setSelectedCalculation] = useState<Calculation | null>(null);
  const [heldResolution, setHeldResolution] = useState({ replacement_calculation_id: '', resolution_ref: '' });
  const [settlement, setSettlement] = useState({ employment_id: '', amount: '', basis: '' });
  const [clearance, setClearance] = useState({ employment_id: '', domain: 'hr', note: '' });

  const load = () => { setLoading(true); setError(null); void getJson<{ data: PayrollWorkspace }>('/payroll/workspace').then((response) => { setData(response.data); setCalculationForm((current) => ({ ...current, period_id: current.period_id || response.data.periods.find((period) => ['open', 'calculating'].includes(period.lifecycle_state ?? ''))?.id || '' })); }).catch((reasonValue: unknown) => setError(reasonValue instanceof Error ? reasonValue.message : 'Payroll workspace could not be loaded.')).finally(() => setLoading(false)); };
  useEffect(load, []);
  const command = (request: Promise<unknown>, success: string) => { setBusy(true); setError(null); setMessage(null); void request.then(() => { setMessage(success); load(); }).catch((reasonValue: unknown) => setError(reasonValue instanceof Error ? reasonValue.message : 'Payroll command was rejected.')).finally(() => setBusy(false)); };
  const visibleCalculations = useMemo(() => { const term = query.trim().toLowerCase(); if (!term) return data?.calculations ?? []; return (data?.calculations ?? []).filter((item) => `${item.id} ${item.employment_id} ${item.lifecycle_state ?? ''} ${item.period_id ?? ''}`.toLowerCase().includes(term)); }, [data, query]);
  const submitPeriod = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); command(postJson('/payroll/periods', periodForm), 'Payroll period opened.'); setPeriodForm({ period_key: '', date_from: '', date_to: '' }); };
  const closePeriod = (period: Period) => { if (!confirmAction(`Close Payroll period ${period.period_key}?`, true)) return; command(postJson(`/payroll/periods/${encodeURIComponent(period.id)}/close`), 'Payroll period closed and locked.'); };
  const calculate = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); command(postJson('/payroll/calculations', calculationForm), 'Payroll calculation prepared from HR contract facts.'); };
  const approve = (calculation: Calculation) => { if (!confirmAction(`Approve Payroll calculation ${calculation.id} as an official result?`, true)) return; command(postJson(`/payroll/calculations/${encodeURIComponent(calculation.id)}/approve`), 'Payroll result approved and versioned.'); setSelectedCalculation(null); };
  const resolveHeld = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selectedCalculation) return; command(postJson(`/payroll/calculations/${encodeURIComponent(selectedCalculation.id)}/resolve-held`, heldResolution), 'Held payroll calculation resolved.'); setHeldResolution({ replacement_calculation_id: '', resolution_ref: '' }); };
  const proposeSettlement = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!settlement.employment_id) return; command(postJson(`/payroll/employments/${encodeURIComponent(settlement.employment_id)}/settlements`, { amount: settlement.amount, basis: settlement.basis }), 'Settlement proposed; Finance remains the monetary settlement authority.'); setSettlement({ employment_id: '', amount: '', basis: '' }); };
  const submitClearance = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!clearance.employment_id) return; command(postJson(`/payroll/employments/${encodeURIComponent(clearance.employment_id)}/clearance`, { domain: clearance.domain, note: clearance.note }), `${humanize(clearance.domain)} clearance recorded.`); setClearance({ employment_id: '', domain: 'hr', note: '' }); };
  const tabs: Array<{ id: Tab; label: string }> = [
    { id: 'overview', label: 'Overview' },
    { id: 'periods', label: 'Periods' },
    { id: 'calculations', label: 'Calculations' },
    { id: 'settlements', label: 'Settlements' },
  ];
  const moveTab = (direction: 1 | -1) => {
    const index = tabs.findIndex((item) => item.id === tab);
    const next = tabs[(index + direction + tabs.length) % tabs.length];
    setTab(next.id);
    window.setTimeout(() => document.getElementById(`payroll-tab-${next.id}`)?.focus(), 0);
  };

  if (loading && !data) return <><AppShell current="finance" csrfToken={csrfToken} /><PageStatus>Loading authoritative Payroll workspace…</PageStatus></>;
  if (!data) return <><AppShell current="finance" csrfToken={csrfToken} /><main id="workspace-main" className="workspace"><div className="alert" role="alert">{error ?? 'Payroll data is unavailable.'}</div></main></>;
  return <><AppShell current="finance" csrfToken={csrfToken} /><main id="payroll-main" className="workspace" aria-labelledby="payroll-title">
    <header className="workspace-header"><div><p className="eyebrow">Payroll · calculation, result, approval</p><h1 id="payroll-title">Calculate first. Recognize later.</h1><p className="lede">Payroll produces governed calculation results. Finance separately recognizes liabilities and records settlement.</p></div><button className="button secondary" type="button" onClick={load} disabled={loading}>Refresh payroll</button></header>
    {error && <div className="alert" role="alert">{error}</div>}{message && <div className="notice" role="status">{message}</div>}
    <section className="summary-grid" aria-label="Payroll summary"><div className="panel"><span className="metric">{data.periods.length}</span><span className="metric-label">Payroll periods</span></div><div className="panel"><span className="metric">{data.calculations.length}</span><span className="metric-label">Calculations</span></div><div className="panel"><span className="metric">{data.calculations.filter((item) => item.lifecycle_state === 'held').length}</span><span className="metric-label">Held calculations</span></div><div className="panel"><span className="metric">{data.results.length}</span><span className="metric-label">Approved results</span></div></section>
    <div className="finance-guard"><strong>Payroll / Finance boundary</strong><span>Payroll results are not ledger entries. Finance owns liability recognition and monetary settlement.</span></div>
    <div className="student-tabs" role="tablist" aria-label="Payroll work areas" onKeyDown={(event) => { if (event.key === 'ArrowRight' || event.key === 'ArrowDown') { event.preventDefault(); moveTab(1); } else if (event.key === 'ArrowLeft' || event.key === 'ArrowUp') { event.preventDefault(); moveTab(-1); } }}>
      {tabs.map((item) => <button key={item.id} id={`payroll-tab-${item.id}`} role="tab" aria-selected={tab === item.id} aria-controls={`payroll-panel-${item.id}`} tabIndex={tab === item.id ? 0 : -1} className={tab === item.id ? 'active' : ''} type="button" onClick={() => setTab(item.id)}>{item.label}{item.id === 'periods' && <span aria-hidden="true">{data.periods.length}</span>}{item.id === 'calculations' && <span aria-hidden="true">{data.calculations.length}</span>}{item.id === 'settlements' && <span aria-hidden="true">{data.settlement_proposals.length}</span>}</button>)}
    </div>
    {(tab === 'overview' || tab === 'periods') && <section id={`payroll-panel-${tab}`} role="tabpanel" tabIndex={0} className="panel"><div className="section-heading"><div><p className="eyebrow">Period lifecycle</p><h2>Payroll periods</h2></div><span className="source-note">Payroll authority controls open and close</span></div><form onSubmit={submitPeriod}><div className="compact-grid"><label>Period key<input required maxLength={40} value={periodForm.period_key} onChange={(event) => setPeriodForm({ ...periodForm, period_key: event.target.value })} placeholder="e.g. 2026-09" /></label><label>From<input required type="date" value={periodForm.date_from} onChange={(event) => setPeriodForm({ ...periodForm, date_from: event.target.value })} /></label><label>To<input required type="date" value={periodForm.date_to} onChange={(event) => setPeriodForm({ ...periodForm, date_to: event.target.value })} /></label><button className="button" type="submit" disabled={busy}>Open period</button></div></form>{data.periods.length === 0 ? <p className="empty">No Payroll periods are visible in this scope.</p> : <div className="table-wrap"><table><thead><tr><th>Period</th><th>Window</th><th>State</th><th>Action</th></tr></thead><tbody>{data.periods.map((period) => <tr key={period.id}><td><strong>{period.period_key}</strong><small>{period.id}</small></td><td>{period.date_from} → {period.date_to}</td><td><span className="status-chip">{humanize(period.lifecycle_state ?? 'recorded')}</span></td><td>{period.lifecycle_state === 'open' || period.lifecycle_state === 'calculating' ? <button className="button secondary" type="button" disabled={busy} onClick={() => closePeriod(period)}>Close period</button> : <span className="muted">Locked</span>}</td></tr>)}</tbody></table></div>}</section>}
    {(tab === 'overview' || tab === 'calculations') && <section id={`payroll-panel-${tab}`} role="tabpanel" tabIndex={0} className="panel"><div className="section-heading"><div><p className="eyebrow">Calculation register</p><h2>Payroll calculations</h2></div><span className="source-note">Amounts are produced by Payroll, never typed here</span></div><label className="directory-filter">Filter calculations<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Calculation, employment, period, state" /></label>{visibleCalculations.length === 0 ? <p className="empty">No Payroll calculation matches the current scope or filter.</p> : <div className="table-wrap"><table><thead><tr><th>Calculation</th><th>Employment</th><th>Base</th><th>State</th><th>Period</th><th>Action</th></tr></thead><tbody>{visibleCalculations.map((calculation) => <tr key={calculation.id} onClick={() => setSelectedCalculation(calculation)} tabIndex={0} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); setSelectedCalculation(calculation); } }}><td><strong>{calculation.id}</strong></td><td>{calculation.employment_id}</td><td>{String(calculation.base_amount ?? 'Produced by Payroll')}</td><td><span className="status-chip">{humanize(calculation.lifecycle_state ?? 'recorded')}</span></td><td>{calculation.period_id ?? '—'}</td><td>{calculation.lifecycle_state === 'prepared' ? <button className="button" type="button" disabled={busy} onClick={(event) => { event.stopPropagation(); approve(calculation); }}>Approve result</button> : calculation.lifecycle_state === 'held' ? <button className="button secondary" type="button" disabled={busy} onClick={(event) => { event.stopPropagation(); setSelectedCalculation(calculation); }}>Resolve hold</button> : <span className="muted">No action</span>}</td></tr>)}</tbody></table></div>}</section>}
    {tab === 'overview' && <section className="finance-command-grid"><section className="panel"><div className="section-heading"><div><p className="eyebrow">Command · calculate</p><h2>Prepare calculation</h2></div><span className="source-note">HR contract rules are resolved by Payroll</span></div><form onSubmit={calculate}><div className="compact-grid"><label>Open period<select required value={calculationForm.period_id} onChange={(event) => setCalculationForm({ ...calculationForm, period_id: event.target.value })}><option value="">Select period…</option>{data.periods.filter((period) => ['open', 'calculating'].includes(period.lifecycle_state ?? '')).map((period) => <option key={period.id} value={period.id}>{period.period_key}</option>)}</select></label><label>Employment ID<input required value={calculationForm.employment_id} onChange={(event) => setCalculationForm({ ...calculationForm, employment_id: event.target.value })} placeholder="HR employment identifier" /></label></div><button className="button" type="submit" disabled={busy}>Prepare calculation</button></form></section><section className="panel"><div className="section-heading"><div><p className="eyebrow">Command · settlement proposal</p><h2>Propose termination settlement</h2></div><span className="source-note">Finance approval remains separate</span></div><form onSubmit={proposeSettlement}><div className="compact-grid"><label>Employment ID<input required value={settlement.employment_id} onChange={(event) => setSettlement({ ...settlement, employment_id: event.target.value })} /></label><label>Proposed amount<input required inputMode="decimal" value={settlement.amount} onChange={(event) => setSettlement({ ...settlement, amount: event.target.value })} /></label><label className="full-width">Basis evidence<input required value={settlement.basis} onChange={(event) => setSettlement({ ...settlement, basis: event.target.value })} /></label></div><button className="button secondary" type="submit" disabled={busy}>Propose settlement</button></form></section></section>}
    {tab === 'settlements' && <section id="payroll-panel-settlements" role="tabpanel" tabIndex={0} className="panel"><div className="section-heading"><div><p className="eyebrow">Termination lifecycle</p><h2>Clearance and settlement proposals</h2></div><span className="source-note">HR / Payroll coordination; Finance remains monetary authority</span></div><div className="compact-grid"><form onSubmit={submitClearance}><div className="compact-grid"><label>Employment ID<input required value={clearance.employment_id} onChange={(event) => setClearance({ ...clearance, employment_id: event.target.value })} /></label><label>Domain<select value={clearance.domain} onChange={(event) => setClearance({ ...clearance, domain: event.target.value })}><option value="hr">HR</option><option value="finance">Finance</option></select></label><label className="full-width">Clearance note<input required value={clearance.note} onChange={(event) => setClearance({ ...clearance, note: event.target.value })} /></label></div><button className="button secondary" type="submit" disabled={busy}>Record clearance</button></form><div><h3>Open settlement proposals</h3>{data.settlement_proposals.length === 0 ? <p className="empty">No settlement proposal is waiting for Finance.</p> : <ul className="compact-list">{data.settlement_proposals.map((item) => <li key={item.id}><span><strong>{item.employment_id} · {item.amount}</strong><small>{item.basis} · prepared by {item.prepared_by ?? 'record unavailable'}</small></span><span className="status-chip">{humanize(item.lifecycle_state ?? 'proposed')}</span></li>)}</ul>}</div></div></section>}
    {selectedCalculation?.lifecycle_state === 'held' && <aside className="panel finance-detail" aria-labelledby="held-title"><div className="section-heading"><div><p className="eyebrow">Held calculation</p><h2 id="held-title">Resolution required</h2></div><button className="text-button" type="button" onClick={() => setSelectedCalculation(null)}>Close</button></div><p className="muted">{selectedCalculation.hold_reason ?? 'The Payroll engine could not establish a complete rule resolution.'}</p><form onSubmit={resolveHeld}><div className="compact-grid"><label>Replacement calculation ID<input required value={heldResolution.replacement_calculation_id} onChange={(event) => setHeldResolution({ ...heldResolution, replacement_calculation_id: event.target.value })} /></label><label className="full-width">Resolution reference<input required value={heldResolution.resolution_ref} onChange={(event) => setHeldResolution({ ...heldResolution, resolution_ref: event.target.value })} /></label></div><button className="button" type="submit" disabled={busy}>Resolve held calculation</button></form></aside>}
  </main></>;
}
if (root) createRoot(root).render(<PayrollApp />);
