import { FormEvent, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AppShell, PageStatus } from './ui';
import { createApiClient } from './core/api';
import type { ApiClient } from './core/api';
import './app.css';

type PlacementProfile = Record<string, unknown> & { id: string; person_id: string; lifecycle_state: string; overall_cefr_ref?: string | null; recommended_level_id?: string | null; current_home_branch_id?: string | null; originating_branch_id?: string | null; person?: { legal_name?: string | null } | null; updated_at?: string | null };
type PlacementAttempt = Record<string, unknown> & { id: string; profile_id: string; attempt_no: number; test_version_id: string; delivery_mode: string; status: string; lineage_version?: number | null; started_at?: string | null; submitted_at?: string | null; tamper_flagged?: boolean };
type SectionResult = Record<string, unknown> & { id: string; attempt_id: string; section_id?: string | null; component: string; raw_score?: string | number | null; rubric_id?: string | null; lifecycle_state: string; evidence_ref?: string | null };
type Recommendation = Record<string, unknown> & { id: string; recommended_level_id: string; rationale?: string | null; lifecycle_state: string; created_at?: string | null; approved_at?: string | null };
type EligibilitySnapshot = Record<string, unknown> & { snapshot_id?: string; lifecycle_state?: string; eligibility?: string; signed_at?: string | null; source?: string | null };
type TestVersion = { id: string; placement_test_id: string; version_no: number; summary: string; lifecycle_state: string; published_at?: string | null };
type ApiProfile = { profile: PlacementProfile; attempts: PlacementAttempt[]; section_results: SectionResult[]; recommendations: Recommendation[]; eligibility_snapshot: EligibilitySnapshot | null };
type AttemptableVersion = { id?: string; version_id?: string; test_version_id?: string; name?: string; summary?: string; version_no?: number; lifecycle_state?: string; delivery_mode?: string };

function humanize(value: string): string { return value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function confirmAction(summary: string, irreversible = false): boolean { return window.confirm(`${summary}\n\n${irreversible ? 'This changes an official placement lifecycle state and may not be reversible.' : 'The server remains the authority for the resulting state.'}\n\nContinue?`); }
function valueOf(item: Record<string, unknown>, keys: string[]): string { for (const key of keys) { const value = item[key]; if (value !== null && value !== undefined && value !== '') return String(value); } return '—'; }

function PlacementDetail({ data, versions, onRefresh, api, csrfToken, onError, onMessage }: { data: ApiProfile; versions: AttemptableVersion[]; onRefresh: () => void; api: ApiClient; csrfToken: string; onError: (message: string) => void; onMessage: (message: string) => void }) {
  const { postJson, getJson } = api;
  const profile = data.profile;
  const [attemptVersion, setAttemptVersion] = useState('');
  const [deliveryMode, setDeliveryMode] = useState<'digital' | 'physical'>('digital');
  const [proctorPersonId, setProctorPersonId] = useState('');
  const [answers, setAnswers] = useState('');
  const [evidenceRef, setEvidenceRef] = useState('');
  const [scoreForm, setScoreForm] = useState({ attempt_id: '', section_id: '', raw_score: '', rubric_id: '', rationale: '' });
  const [busy, setBusy] = useState(false);
  const [financeLink, setFinanceLink] = useState<Record<string, unknown> | null>(null);

  useEffect(() => { setAttemptVersion(versions[0]?.id ?? versions[0]?.version_id ?? versions[0]?.test_version_id ?? ''); }, [versions]);
  useEffect(() => {
    setScoreForm((current) => ({ ...current, attempt_id: data.attempts.find((item) => item.status === 'submitted')?.id ?? '' }));
    void getJson<Record<string, unknown>>(`/placement/profiles/${encodeURIComponent(profile.id)}/finance-link`).then(setFinanceLink).catch(() => setFinanceLink(null));
  }, [profile.id, data.attempts, getJson]);

  const command = (path: string, body: Record<string, unknown> | undefined, success: string, confirmation?: string, irreversible = false) => {
    if (confirmation && !confirmAction(confirmation, irreversible)) return;
    setBusy(true); onError('');
    void postJson(path, body).then(() => { onMessage(success); onRefresh(); }).catch((reason: unknown) => onError(reason instanceof Error ? reason.message : 'Placement command was rejected by the server.')).finally(() => setBusy(false));
  };
  const startAttempt = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!attemptVersion) return; command('/placement/attempts', { profile_id: profile.id, test_version_id: attemptVersion, delivery_mode: deliveryMode, proctor_person_id: proctorPersonId || undefined }, 'Placement attempt started.'); };
  const submitDigital = (attempt: PlacementAttempt) => { const parsed = answers.split('\n').map((line) => line.trim()).filter(Boolean); if (!parsed.length) { onError('Enter one answer per line before submitting the digital attempt.'); return; } command(`/placement/attempts/${encodeURIComponent(attempt.id)}/submit`, { answers: parsed }, 'Digital attempt submitted; the server owns scoring.'); };
  const submitPhysical = (attempt: PlacementAttempt) => { if (!evidenceRef.trim()) { onError('Evidence reference is required for a physical submission.'); return; } command(`/placement/attempts/${encodeURIComponent(attempt.id)}/submit-physical`, { evidence_ref: evidenceRef.trim() }, 'Physical evidence recorded; professional marking remains separate.'); };
  const cancelAttempt = (attempt: PlacementAttempt) => command(`/placement/attempts/${encodeURIComponent(attempt.id)}/cancel`, undefined, 'Placement attempt cancelled.', `Cancel attempt ${attempt.attempt_no}?`, true);
  const score = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); command('/placement/sections/score', { ...scoreForm, raw_score: Number(scoreForm.raw_score) }, 'Section score recorded by the placement scoring authority.'); };

  return <main id="workspace-main" className="workspace" aria-labelledby="placement-detail-title">
    <header className="workspace-header"><div><p className="eyebrow">Placement decision lifecycle</p><h1 id="placement-detail-title">{(profile.person as { legal_name?: string | null } | undefined)?.legal_name ?? profile.person_id}</h1><p className="lede">Evidence → score → recommendation → decision → eligibility. Enrollment remains an Academic authority downstream.</p></div><a className="button secondary" href="/placement">Back to placement directory</a></header>
    <section className="summary-grid"><div className="panel"><span className="metric">{humanize(profile.lifecycle_state)}</span><span className="metric-label">Current placement state</span></div><div className="panel"><span className="metric">{data.attempts.length}</span><span className="metric-label">Attempts</span></div><div className="panel"><span className="metric">{data.section_results.length}</span><span className="metric-label">Section evidence</span></div><div className="panel"><span className="metric">{data.recommendations.length}</span><span className="metric-label">Recommendations</span></div></section>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Placement identity</p><h2>Provenance and current decision state</h2></div><span className="status-chip">{humanize(profile.lifecycle_state)}</span></div><dl className="detail-facts"><div><dt>Profile</dt><dd>{profile.id}</dd></div><div><dt>Person</dt><dd>{profile.person_id}</dd></div><div><dt>Origin branch</dt><dd>{valueOf(profile, ['originating_branch_id'])}</dd></div><div><dt>Current home branch</dt><dd>{valueOf(profile, ['current_home_branch_id'])}</dd></div><div><dt>CEFR evidence</dt><dd>{valueOf(profile, ['overall_cefr_ref'])}</dd></div><div><dt>Recommended level</dt><dd>{valueOf(profile, ['recommended_level_id'])}</dd></div></dl></section>
    {profile.lifecycle_state !== 'released' && versions.length > 0 && <section className="panel"><div className="section-heading"><div><p className="eyebrow">Evidence capture</p><h2>Start a governed attempt</h2></div><span className="source-note">Version eligibility is computed server-side.</span></div><form onSubmit={startAttempt}><div className="compact-grid"><label>Published test version<select required value={attemptVersion} onChange={(event) => setAttemptVersion(event.target.value)}><option value="">Select a version…</option>{versions.map((version, index) => { const id = version.id ?? version.version_id ?? version.test_version_id ?? ''; return <option key={`${id}-${index}`} value={id}>{version.version_no ? `v${version.version_no} · ` : ''}{version.summary ?? version.name ?? id}</option>; })}</select></label><label>Delivery mode<select value={deliveryMode} onChange={(event) => setDeliveryMode(event.target.value as 'digital' | 'physical')}><option value="digital">Digital</option><option value="physical">Physical</option></select></label>{deliveryMode === 'physical' && <label>Proctor person id<input required value={proctorPersonId} onChange={(event) => setProctorPersonId(event.target.value)} /></label>}</div><button className="button" type="submit" disabled={busy || !attemptVersion}>{busy ? 'Starting…' : 'Start attempt'}</button></form></section>}
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Attempts</p><h2>Evidence delivery</h2></div><span className="source-note">Submission does not itself imply recommendation or enrollment eligibility.</span></div>{data.attempts.length === 0 ? <p className="empty">No placement attempt has been recorded.</p> : <ul className="fact-list">{data.attempts.map((attempt) => <li key={attempt.id}><div><strong>Attempt {attempt.attempt_no} · {humanize(attempt.delivery_mode)}</strong><span>{humanize(attempt.status)} · version {attempt.test_version_id}{attempt.tamper_flagged ? ' · duration envelope flagged' : ''}</span></div><div className="inline-actions">{attempt.status === 'in_progress' && attempt.delivery_mode === 'digital' && <><label><span className="sr-only">Answers for attempt {attempt.attempt_no}</span><textarea value={answers} onChange={(event) => setAnswers(event.target.value)} rows={2} placeholder="One answer per line" /></label><button className="button" type="button" disabled={busy} onClick={() => submitDigital(attempt)}>Submit digital evidence</button></>}{attempt.status === 'in_progress' && attempt.delivery_mode === 'physical' && <><label><span className="sr-only">Evidence reference</span><input value={evidenceRef} onChange={(event) => setEvidenceRef(event.target.value)} placeholder="Immutable evidence reference" /></label><button className="button" type="button" disabled={busy} onClick={() => submitPhysical(attempt)}>Submit physical evidence</button></>}{['in_progress', 'submitted'].includes(attempt.status) && <button className="text-button" type="button" disabled={busy} onClick={() => cancelAttempt(attempt)}>Cancel attempt</button>}</div></li>)}</ul>}</section>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Scoring evidence</p><h2>Section results</h2></div><span className="source-note">Professional marks require rubric and rationale; CEFR is not accepted from the client.</span></div>{data.section_results.length === 0 ? <p className="empty">No section result is visible yet.</p> : <ul className="fact-list">{data.section_results.map((result) => <li key={result.id}><div><strong>{humanize(result.component)} · {valueOf(result, ['raw_score'])}</strong><span>{humanize(result.lifecycle_state)} · rubric {valueOf(result, ['rubric_id'])} · evidence {valueOf(result, ['evidence_ref'])}</span></div><div className="inline-actions">{result.lifecycle_state === 'scored' && <><button className="text-button" type="button" disabled={busy} onClick={() => command(`/placement/section-results/${encodeURIComponent(result.id)}/moderate`, undefined, 'Section moderated.')}>Moderate</button><button className="text-button" type="button" disabled={busy} onClick={() => command(`/placement/section-results/${encodeURIComponent(result.id)}/approve`, undefined, 'Section approved.')}>Approve section</button></>}</div></li>)}</ul>}
      {data.attempts.some((attempt) => attempt.status === 'submitted') && <form onSubmit={score} className="action-form"><div className="compact-grid"><label>Submitted attempt<select required value={scoreForm.attempt_id} onChange={(event) => setScoreForm({ ...scoreForm, attempt_id: event.target.value })}><option value="">Select attempt…</option>{data.attempts.filter((attempt) => attempt.status === 'submitted').map((attempt) => <option key={attempt.id} value={attempt.id}>Attempt {attempt.attempt_no}</option>)}</select></label><label>Section id<input required value={scoreForm.section_id} onChange={(event) => setScoreForm({ ...scoreForm, section_id: event.target.value })} /></label><label>Raw score<input required inputMode="decimal" value={scoreForm.raw_score} onChange={(event) => setScoreForm({ ...scoreForm, raw_score: event.target.value })} /></label><label>Rubric id<input required value={scoreForm.rubric_id} onChange={(event) => setScoreForm({ ...scoreForm, rubric_id: event.target.value })} /></label><label className="full-width">Rationale<input required value={scoreForm.rationale} onChange={(event) => setScoreForm({ ...scoreForm, rationale: event.target.value })} /></label></div><button className="button" type="submit" disabled={busy}>Record professional score</button></form>}</section>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Decision authority</p><h2>From scored evidence to eligibility</h2></div><span className="source-note">Recommendation is not enrollment.</span></div><div className="inline-actions"><button className="button secondary" type="button" disabled={busy} onClick={() => command(`/placement/profiles/${encodeURIComponent(profile.id)}/mark-scored`, undefined, 'Profile marked scored.')}>Mark scored</button><button className="button secondary" type="button" disabled={busy} onClick={() => command(`/placement/profiles/${encodeURIComponent(profile.id)}/recommend`, undefined, 'Recommendation generated.')}>Generate recommendation</button><button className="button secondary" type="button" disabled={busy} onClick={() => command(`/placement/profiles/${encodeURIComponent(profile.id)}/review`, undefined, 'Placement reviewed.')}>Review decision</button><button className="button" type="button" disabled={busy} onClick={() => command(`/placement/profiles/${encodeURIComponent(profile.id)}/approve`, undefined, 'Placement decision approved.', 'Approve this placement decision based on the recorded evidence?', true)}>Approve decision</button><button className="button" type="button" disabled={busy} onClick={() => command(`/placement/profiles/${encodeURIComponent(profile.id)}/release`, undefined, 'Placement released as an official result.', 'Release this placement result to downstream consumers?', true)}>Release result</button></div>{data.recommendations.length === 0 ? <p className="empty">No placement recommendation has been issued.</p> : <ul className="fact-list">{data.recommendations.map((recommendation) => <li key={recommendation.id}><strong>Recommended level: {recommendation.recommended_level_id}</strong><span>{humanize(recommendation.lifecycle_state)} · {recommendation.rationale ?? 'No rationale supplied'} · {recommendation.created_at ?? 'timestamp unavailable'}</span></li>)}</ul>}</section>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Downstream consumption</p><h2>Signed eligibility snapshot</h2></div><span className="source-note">Academic enrollment consumes eligibility; it does not originate here.</span></div>{data.eligibility_snapshot ? <dl className="detail-facts">{Object.entries(data.eligibility_snapshot).map(([key, value]) => <div key={key}><dt>{humanize(key)}</dt><dd>{typeof value === 'object' ? JSON.stringify(value) : String(value ?? '—')}</dd></div>)}</dl> : <p className="empty">No signed eligibility snapshot exists. This UI does not infer one from recommendation or score.</p>}</section>
    {financeLink && <section className="panel"><div className="section-heading"><div><p className="eyebrow">Finance projection</p><h2>Related monetary facts</h2></div><span className="source-note">Finance remains the sole monetary authority.</span></div><dl className="detail-facts">{Object.entries(financeLink).map(([key, value]) => <div key={key}><dt>{humanize(key)}</dt><dd>{Array.isArray(value) ? `${value.length} record(s)` : typeof value === 'object' && value !== null ? JSON.stringify(value) : String(value ?? '—')}</dd></div>)}</dl></section>}
  </main>;
}

function PlacementApp({ getJson, postJson, csrfToken }: ApiClient & { csrfToken: string }) {
  const [profiles, setProfiles] = useState<PlacementProfile[]>([]);
  const [tests, setTests] = useState<PlacementProfile[]>([]);
  const [versions, setVersions] = useState<TestVersion[]>([]);
  const [selected, setSelected] = useState<ApiProfile | null>(null);
  const [attemptable, setAttemptable] = useState<AttemptableVersion[]>([]);
  const [query, setQuery] = useState('');
  const [state, setState] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [openForm, setOpenForm] = useState({ person_id: '', program_version_id: '', visitor_id: '', branch_id: '' });
  const [busy, setBusy] = useState(false);
  const load = () => { setLoading(true); setError(null); void Promise.all([getJson<{ profiles: PlacementProfile[] }>(`/placement/profiles?term=${encodeURIComponent(query)}&lifecycle_state=${encodeURIComponent(state)}`), getJson<{ tests: PlacementProfile[] }>('/placement/tests'), getJson<{ versions: TestVersion[] }>('/placement/versions')]).then(([p, t, v]) => { setProfiles(p.profiles ?? []); setTests(t.tests ?? []); setVersions(v.versions ?? []); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Placement workspace could not be loaded.')).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, [query, state]);
  const openProfile = (profile: PlacementProfile) => { setError(null); setMessage(null); void getJson<ApiProfile>(`/placement/profiles/${encodeURIComponent(profile.id)}`).then((response) => { setSelected(response); return getJson<{ versions: AttemptableVersion[] }>(`/placement/profiles/${encodeURIComponent(profile.id)}/attemptable-versions`); }).then((response) => setAttemptable(response.versions ?? [])).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Placement profile could not be opened.')); };
  const createProfile = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(null); void postJson('/placement/profiles', { ...openForm, program_version_id: openForm.program_version_id || undefined, visitor_id: openForm.visitor_id || undefined }).then(() => { setOpenForm({ person_id: '', program_version_id: '', visitor_id: '', branch_id: '' }); setMessage('Placement profile opened.'); load(); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Placement profile could not be opened.')).finally(() => setBusy(false)); };
  const visibleProfiles = useMemo(() => profiles, [profiles]);
  if (selected) return <><AppShell current="academic" csrfToken={csrfToken} /><PlacementDetail data={selected} versions={attemptable} onRefresh={() => openProfile(selected.profile)} api={{ getJson, postJson }} csrfToken={csrfToken} onError={(text) => setError(text || null)} onMessage={(text) => setMessage(text)} /></>;
  if (loading) return <><AppShell current="academic" csrfToken={csrfToken} /><PageStatus>Loading authorized Placement evidence…</PageStatus></>;
  return <><AppShell current="academic" csrfToken={csrfToken} /><main id="workspace-main" className="workspace" aria-labelledby="placement-title">
    <header className="workspace-header"><div><p className="eyebrow">Academic Placement</p><h1 id="placement-title">Evidence first. Decisions second.</h1><p className="lede">Placement evaluates evidence and produces a governed recommendation/eligibility result. It does not enroll students or assign classes.</p></div><button className="button secondary" type="button" onClick={load}>Refresh placement facts</button></header>
    {error && <div className="alert" role="alert">{error}</div>}{message && <div className="notice" role="status">{message}</div>}
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Open profile</p><h2>Start a placement decision chain</h2></div><span className="source-note">Server validates identity, program compatibility, scope, audit and idempotency.</span></div><form onSubmit={createProfile}><div className="compact-grid"><label>Person id<input required value={openForm.person_id} onChange={(event) => setOpenForm({ ...openForm, person_id: event.target.value })} /></label><label>Program version<input value={openForm.program_version_id} onChange={(event) => setOpenForm({ ...openForm, program_version_id: event.target.value })} placeholder="Optional" /></label><label>Visitor id<input value={openForm.visitor_id} onChange={(event) => setOpenForm({ ...openForm, visitor_id: event.target.value })} placeholder="Optional" /></label><label>Operational branch id<input required value={openForm.branch_id} onChange={(event) => setOpenForm({ ...openForm, branch_id: event.target.value })} /></label></div><button className="button" type="submit" disabled={busy}>{busy ? 'Opening…' : 'Open placement profile'}</button></form></section>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Authorized placement register</p><h2>Profiles in evidence lifecycle</h2></div><span className="source-note">{profiles.length} visible · conduct scope enforced server-side</span></div><div className="compact-grid"><label>Search profile<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Person name or identity key" /></label><label>Lifecycle state<select value={state} onChange={(event) => setState(event.target.value)}><option value="">All states</option>{['open','in_progress','scored','recommended','reviewed','approved','released','superseded'].map((value) => <option key={value} value={value}>{humanize(value)}</option>)}</select></label></div>{visibleProfiles.length === 0 ? <p className="empty">No placement profile matches the current scope and filters.</p> : <div className="table-wrap"><table><thead><tr><th>Person</th><th>State</th><th>CEFR</th><th>Recommended level</th><th>Updated</th><th>Action</th></tr></thead><tbody>{visibleProfiles.map((profile) => <tr key={profile.id}><td><strong>{profile.person?.legal_name ?? profile.person_id}</strong><small>{profile.person_id}</small></td><td><span className="status-chip">{humanize(profile.lifecycle_state)}</span></td><td>{profile.overall_cefr_ref ?? '—'}</td><td>{profile.recommended_level_id ?? '—'}</td><td>{profile.updated_at ?? '—'}</td><td><button className="text-button" type="button" onClick={() => openProfile(profile)}>Open evidence chain</button></td></tr>)}</tbody></table></div>}</section>
    <section className="summary-grid"><div className="panel"><span className="metric">{tests.length}</span><span className="metric-label">Visible placement tests</span></div><div className="panel"><span className="metric">{versions.length}</span><span className="metric-label">Catalog versions</span></div><div className="panel"><span className="metric">API</span><span className="metric-label">Placement authority</span></div><div className="panel"><span className="metric">No</span><span className="metric-label">Enrollment authority here</span></div></section>
  </main></>;
}

const root = document.getElementById('placement-console');
if (root) { const csrfToken = root.getAttribute('data-csrf-token') ?? ''; const api = createApiClient({ apiBase: root.getAttribute('data-api-base') ?? '/api/v1', csrfToken }); createRoot(root).render(<PlacementApp {...api} csrfToken={csrfToken} />); }
