import { FormEvent, useEffect, useMemo, useState } from 'react';
import { AppShell, Icon, PageStatus } from './ui';
import type { ApiClient } from './core/api';

type ApiEnvelope<T> = { data: T };
type Me = { username: string; person_id: string; display_name: string };
type Position = { id: string; position_id: string; position_name: string; effective_from: string; effective_to: string | null };
type WorkItem = { id?: string; organization_id?: string | null; branch_id?: string | null; kind: string; source_type: string; source_id: string; title: string; status: string; due_at: string | null; route: string; reason?: string | null };
type NotificationItem = { id: string; source_type: string; source_id: string; title: string; body_ref: string | null; severity: string; status: string; read_at: string | null; created_at: string | null };
type EmployeeWorkspace = { actor: { id: string; display_name: string }; positions: Position[]; scope: { organization_ids: string[]; branch_ids: string[]; scope_known: boolean }; work: { items: WorkItem[]; count: number }; notifications: { status: string; unread_count: number; items: NotificationItem[] }; generated_at: string };
type SearchResult = { type: string; id: string; label: string; secondary: string; status?: string; route: string };
type SearchResponse = { term: string; results: SearchResult[]; scope: { branch_ids: string[]; scope_known: boolean } };
function humanize(value: string): string { return value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()); }

export function WorkspaceApp({ getJson, postJson, csrfToken }: ApiClient & { csrfToken: string }) {
  const [me, setMe] = useState<Me | null>(null);
  const [workspace, setWorkspace] = useState<EmployeeWorkspace | null>(null);
  const [query, setQuery] = useState('');
  const [search, setSearch] = useState<SearchResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [searching, setSearching] = useState(false);
  useEffect(() => {
    void Promise.all([getJson<ApiEnvelope<Me>>('/me'), getJson<ApiEnvelope<EmployeeWorkspace>>('/workspace')]).then(([meResponse, workspaceResponse]) => { setMe(meResponse.data); setWorkspace(workspaceResponse.data); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'The workspace could not be loaded.')).finally(() => setLoading(false));
  }, [getJson]);
  const reloadWorkspace = () => getJson<ApiEnvelope<EmployeeWorkspace>>('/workspace').then((response) => setWorkspace(response.data));
  const submitSearch = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const term = query.trim(); if (term.length < 2) { setSearch(null); return; } setSearching(true); setError(null); void getJson<ApiEnvelope<SearchResponse>>(`/search?q=${encodeURIComponent(term)}`).then((response) => setSearch(response.data)).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Search could not be completed.')).finally(() => setSearching(false)); };
  const markNotification = (id: string, state: 'read' | 'dismiss') => { setError(null); void postJson(`/notifications/${encodeURIComponent(id)}/${state}`).then(reloadWorkspace).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Notification state could not be changed.')); };
  const transitionWorkItem = (item: WorkItem, state: string) => { if (!item.id) return; setError(null); void postJson(`/work-items/${encodeURIComponent(item.id)}/transition`, { to_state: state }).then(reloadWorkspace).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Work state could not be changed.')); };
  const openItems = useMemo(() => workspace?.work.items ?? [], [workspace]);
  if (loading) return <><AppShell current="workspace" csrfToken={csrfToken} /><PageStatus>Loading your authorized workspace…</PageStatus></>;
  return <><AppShell current="workspace" csrfToken={csrfToken} /><main id="workspace-main" className="workspace" aria-labelledby="workspace-title">
    <header className="workspace-header"><div><p className="eyebrow">Employee console</p><h1 id="workspace-title">Good work starts with the next action.</h1><p className="lede">{me ? `Signed in as ${me.display_name}.` : 'Your authorized work and decisions.'}</p></div><a className="button secondary" href="/management">Open management health</a></header>
    {error && <div className="alert" role="alert">{error}</div>}
    <form className="search" onSubmit={submitSearch} role="search"><label htmlFor="workspace-search">Search visible students and visitors</label><div className="search-row"><input id="workspace-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Name, student code, visitor code, email, or phone" /><button className="button" type="submit" disabled={searching}>{searching ? 'Searching…' : 'Search'}</button></div>{search && <div className="search-results" aria-live="polite"><strong>{search.results.length} result{search.results.length === 1 ? '' : 's'}</strong>{search.results.length === 0 ? <p className="muted">No matching record in your visible branches.</p> : <ul>{search.results.map((result) => <li key={`${result.type}-${result.id}`}><a href={result.route}>{result.label}</a><span>{result.secondary}{result.status ? ` · ${result.status}` : ''}</span></li>)}</ul>}</div>}</form>
    <section className="summary-grid" aria-label="Workspace summary"><div className="panel"><span className="metric">{openItems.length}</span><span className="metric-label">Open work items</span></div><div className="panel"><span className="metric">{workspace?.positions.length ?? 0}</span><span className="metric-label">Effective positions</span></div><div className="panel"><span className="metric">{workspace?.scope.branch_ids.length ?? 0}</span><span className="metric-label">Visible branches</span></div><div className="panel"><span className="metric">{workspace?.scope.organization_ids.length ?? 0}</span><span className="metric-label">Authorized organizations</span></div></section>
    <section aria-label="Common work areas"><div className="section-heading"><div><p className="eyebrow">Quick access</p><h2>Move to the work</h2></div><span className="source-note">Navigation follows the operator's work, not the database.</span></div><div className="quick-actions"><a className="quick-action" href="/students"><span className="quick-icon" aria-hidden="true"><Icon name="users" /></span><span><strong>Students & admissions</strong><small>Directory, applications and lifecycle</small></span></a><a className="quick-action" href="/academic"><span className="quick-icon" aria-hidden="true"><Icon name="academic" /></span><span><strong>Academic operations</strong><small>Classes, capacity, sessions and outcomes</small></span></a><a className="quick-action" href="/crm"><span className="quick-icon" aria-hidden="true"><Icon name="crm" /></span><span><strong>CRM</strong><small>Visitors, follow-up and conversations</small></span></a><a className="quick-action" href="/finance"><span className="quick-icon" aria-hidden="true"><Icon name="finance" /></span><span><strong>Finance</strong><small>Source-owned monetary operations</small></span></a></div></section>
    <section className="panel" aria-labelledby="notifications-heading"><div className="section-heading"><div><p className="eyebrow">Recipient projection</p><h2 id="notifications-heading">Notifications {workspace?.notifications.unread_count ? `· ${workspace.notifications.unread_count} unread` : ''}</h2></div><span className="source-note">Read state is recipient-owned</span></div>{(workspace?.notifications.items.length ?? 0) === 0 ? <p className="empty">No active notifications.</p> : <ul className="notification-list">{workspace?.notifications.items.map((notification) => <li key={notification.id} className={notification.status === 'unread' ? 'unread' : ''}><div><strong>{notification.title}</strong><small>{notification.source_type} · {notification.source_id}</small></div><div className="notification-actions">{notification.status === 'unread' && <button className="text-button" type="button" onClick={() => markNotification(notification.id, 'read')}>Mark read</button>}<button className="text-button" type="button" onClick={() => markNotification(notification.id, 'dismiss')}>Dismiss</button></div></li>)}</ul>}</section>
    <section className="panel" aria-labelledby="work-heading"><div className="section-heading"><div><p className="eyebrow">Canonical sources</p><h2 id="work-heading">Your work queue</h2></div><span className="source-note">Read projection · mutations stay in owning modules</span></div>{openItems.length === 0 ? <p className="empty">No open work was found in your current effective scope.</p> : <ul className="work-list">{openItems.map((item, index) => <li key={item.id ?? `${item.source_type}-${item.source_id}-${index}`}><div><span className="kind">{humanize(item.kind)}</span><a href={item.route}>{item.title}</a><small>{item.source_type} · {item.source_id}{item.branch_id ? ` · branch ${item.branch_id}` : item.organization_id ? ` · organization ${item.organization_id}` : ''}</small></div><div className="work-actions"><span className={`status-chip ${item.status}`}>{humanize(item.status)}</span>{item.id && item.status === 'open' && <button className="text-button" type="button" onClick={() => transitionWorkItem(item, 'claimed')}>Claim</button>}{item.id && item.status === 'claimed' && <button className="text-button" type="button" onClick={() => transitionWorkItem(item, 'in_progress')}>Start</button>}{item.id && item.status === 'in_progress' && <button className="text-button" type="button" onClick={() => transitionWorkItem(item, 'completed')}>Complete coordination</button>}</div></li>)}</ul>}</section>
  </main></>;
}
